### PR TITLE
Account creation created

### PR DESCRIPTION
**Pull request by Jlweatherly0802**
added account app to create user

### CODE REVIEW

**Comment by codeurimpulsif** [comment]
Hi @Jlweatherly0802, I don't really understand why creating such thing? We can already create new accounts from Django administration page.

Also, please look at Flake8 linter, thanks.

**Comment by Jlweatherly0802** [comment]
this was the issue i was addressing

https://github.com/Exodus-Privacy/etip/issues/190

**Comment by codeurimpulsif** [comment]
I think you misunderstood, the purpose of this issue is not to create accounts but to edit your own account.

**Comment by Jlweatherly0802** [comment]
@codeurimpulsif ok the admins create non-admin accounts and then those none admin accounts need to adjust there data

**Pull request closed without merging**
