### PR TITLE
Add flake8 to ci

### PR DESCRIPTION
**Pull request by nautikos1235**
Fixes https://github.com/Exodus-Privacy/etip/issues/45

### CODE REVIEW

**Comment by simpnu** [comment]
Thank you @nautikos1235 for your PR <3

Seems like the new travis CI configuration file doesn't use the specified python versions and only runs on one version of python (see https://travis-ci.org/Exodus-Privacy/etip/jobs/552438725).

Could you please check to fix that ?

**Comment by nautikos1235** [comment]
Travis syntax is quite weird, but well it looks ok now =)

**Comment by simpnu** [comment]
According to https://docs.travis-ci.com/user/build-stages/ it seems like these stages make sense if you want to run jobs one after the other (such as compile before test). Here I think we want to run the tests and linter in parallel.

I would either do:
```
script:
- cd etip/
- flake8
- python manage.py test
```
to have the multiple scripts ran in one job
OR
```
jobs:
  include:
    - script:
        - cd etip/
        - python manage.py test
    - script:
        - flake8 etip/
```
to have the multiple scripts ran in parallel in the same stage (default stage being "test")

WDYT?

**Comment by nautikos1235** [comment]
Updated so that all jobs get run at the same time (at stage Test).
The updated file allows to run tests in python 3.5 and 3.6, but flake8 only once (with python 3.6).

**Comment by simpnu** [comment]
I'm wondering whether this should work:

```
language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO_SETTINGS_MODULE=etip.settings.dev

install:
  - pip install -r requirements.txt

jobs:
  include:
    - script
        - flake8 etip/
      python: 3.6
      install:
        - pip install flake8
    - script:
        - cd etip/
        - python manage.py test
```

**Comment by nautikos1235** [comment]
Here is the weird behavior happening with your suggestion:
https://travis-ci.org/Exodus-Privacy/etip/builds/552888800

I will revert to something that works ^^

**Comment by simpnu** [comment]
Alright, I'll merge this as is because it does what we want.
We'll see to improve it later, if it is even possible.

Thanks for your efforts on this @nautikos1235 :)

**Pull request merged**
